---
channel: stable
addons:
  n8n:
    repository: pedrol3001/addon-n8n
    target: n8n
    image: ghcr.io/pedrol3001/n8n/{arch}
  semaphore:
    repository: pedrol3001/addon-semaphore
    target: semaphore
    image: ghcr.io/pedrol3001/semaphore/{arch}
  redis:
    repository: pedrol3001/addon-redis
    target: redis
    image: ghcr.io/pedrol3001/redis/{arch}
  collabora:
    repository: pedrol3001/addon-collabora
    target: collabora
    image: ghcr.io/pedrol3001/collabora/{arch}
  rustdesk:
    repository: pedrol3001/addon-rustdesk
    target: rustdesk
    image: ghcr.io/pedrol3001/rustdesk/{arch}
